# UDFRUN:cartera-Posicion-Calif_Actinver
# This code was generated by UDFRun, please do not modify it
from app import app
from flask import request, jsonify


@app.route('/api/v1/udf/Calif_Actinver', methods=['GET'])
def api_id_Calif_Actinver():
  parameters = request.args
  emisora = parameters.get('emisora')
  serie = parameters.get('serie')

  global calif
  calif = 'NA'
  if emisora == 'CETES':
    calif = 'A '
  elif emisora == 'BONDESD':
    calif = 'B '
  else:
    if emisora == 'BPAG91':
      if serie == '220428':
        calif = 'B-'
      else:
        calif = 'A '
  return calif


# UDFRUN:End of generated code
